x = "Hello World"  # str
x = 20  # int
x = 20.5  # floate
x = ["apple", "banana", "cherry"]  # list
x = ("apple", "banana", "cherry")  # tuple
x = {name: "Atitaya", age: 20}  # dict
x = {"apple", "banana", "cherry"}  # set
x = frozenset({"apple", "banana", "cherry"})  # frozenset
x = True  # bool
x = b"hello"  # bytes
